// export const iconScreens = {
//     'park': 'Park',
//     'local-cafe': 'CafeScreen',
//     'restaurant': 'RestaurantScreen',
//     'shopping-cart': 'ShoppingScreen',
//     'car-rental': 'CarRentalScreen',
//     'cleaning-services': 'CleaningServicesScreen',
//     'child-friendly': 'ChildFriendlyScreen',
//     'hotel': 'HotelScreen',
//     'money': 'BankScreen',
//     'car-repair': 'CarRepairScreen',
//     'Tour': 'TourScreen',
//     'Dine Out': 'DineOutScreen',
//     'Relax': 'RelaxScreen',
//     'Clothing': 'ClothingScreen',
//     'Others': 'OthersScreen',
//     'Tour' :'Tour',
//     'Dine Out' :'DineOut',
//     'Relax' :'Relax',
//     'Clothing' :'Clothing',
//     'Others' :'Others',
//   };